### ISSUE TITLE
Re-organize functions

### ISSUE THREAD

**Issue by hong-meiling-2002** [perpetualCreations/raspbot-rca#14]
Throughout the process of building this project, managing the large number of software components has been difficult, especially when they're cobbled into one or two files. Expanding them outwards into separate script modules would save the headache of both creating the rest of the project, and maintaining it.

**Comment by perpetualCreations** [comment]
Client software re-organized into modules.

**Comment by perpetualCreations** [comment]
This was finished two months ago, closing the issue. The host has also been re-organized.
