### ISSUE TITLE
Multi-bot Support

### ISSUE THREAD

**Issue by hong-meiling-2002** [perpetualCreations/raspbot-rca#4]
Component creates a launcher for running parallel sessions and modified host and configurations to support this, to let users control multiple bots.
Targeted for release in v1.2.1.

**Comment by TaianC** [comment]
Pushing back to v1.2.2.

**Comment by perpetualCreations** [comment]
Cleaning up old issues, I don't even have the hardware for this. This is not a very viable enhancement, since I lack the resources and time to build a second Raspbot. Unfortunately, closed.

Perhaps one day I can dream of two battery explosions instead of just one.
