### ISSUE TITLE
Re-implement distance check for navigation.

### ISSUE THREAD

**Issue by hong-meiling-2002** [perpetualCreations/raspbot-rca#8]
Should be noted navigation scripting and syntax of navigation commands will be needed to be updated. Additionally a hardware check should be added as well.
Not planned for release in v1.2.1, maybe introduced later as a hotfix once everything has stabilized and validated for usage.

**Comment by perpetualCreations** [comment]
Not sure what this issue was originally made for, having been made over 6 months ago.
Scripting seems just fine, and a hardware check is implemented on the client-side.
