### ISSUE TITLE
Code Documentation, with Sphinx

### ISSUE THREAD

**Issue by hong-meiling-2002** [perpetualCreations/raspbot-rca#9]
Title says it all: generate documentation and export as HTML, then integrate into @perpetualCreations/dreamerslegacy-site repository.
Note to @perpetualCreations, remember to pull changes back to local repository on home PC, and apply changes through WinSCP to Skynet Server.
`sudo service apache2 restart` when you're done.

**Comment by perpetualCreations** [comment]
Not happening, #15.

**Comment by perpetualCreations** [comment]
Code documentation seems verbose for a non-API software application.
